# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

# name: Build and deploy Node.js app to Azure Web App - bagg

# on:
#   push:
#     branches:
#       - main
#   workflow_dispatch:

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v2

#       - name: Set up Node.js version
#         uses: actions/setup-node@v1
#         with:
#           node-version: '18.x'

#       - name: npm install, build, and test
#         run: |
#           npm install
#           npm run build

#       - name: Zip all files for upload between jobs
#         run: zip next.zip ./* .next .env -qr

#       - name: 'Deploy to Azure Web App'
#         id: deploy-to-webapp
#         uses: azure/webapps-deploy@v2
#         with:
#           app-name: 'bagg'
#           slot-name: 'Production'
#           publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_37A3DD4D42CD4220B5FDF77C30340EC7 }}
#           package: next.zip

name: Build and deploy Node.js app to Azure Web App - bagg

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Zip all files for upload
        run: zip -r next.zip ./*

  cypress-test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Install dependencies
        run: npm install

      - name: Start server
        run: npm start &
        background: true

      - name: Wait for server to start
        run: sleep 30s

      - name: Run Cypress tests
        uses: cypress-io/github-action@v2
        with:
          start: npm start

  deploy:
    runs-on: ubuntu-latest
    needs: [build, cypress-test]

    steps:
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'bagg'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_37A3DD4D42CD4220B5FDF77C30340EC7 }}
          package: next.zip
